name: objaxdp
channels: 
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - pytorch::pytorch==1.11
  - pytorch::torchvision
  - conda-forge::cudatoolkit
  - conda-forge::cudnn==8.2.1.32
  - conda-forge::wandb
  - conda-forge::scikit-learn
  - conda-forge::scikit-image
  - conda-forge::nibabel
  - conda-forge::nilearn
  - nvidia::cuda-nvcc
  - ipykernel
  - matplotlib
  - conda-forge::h5py
  - conda-forge::pandas
  - conda-forge::opacus
  - conda-forge::seaborn
  - black
  - pytest
  - pylint
  - pip
  - pip: 
    - hydra-core==1.2.0
    - tqdm 
    - perflint
    - pytest-profiling
    - deepee
    - split-folders
    - pyyaml
    - lpips
    - kornia
    - autodp