name: objaxdp_cpu
channels: 
  - conda-forge
  - pytorch
dependencies:
  - python==3.10
  - pytorch::pytorch==1.11
  - pytorch::torchvision
  - pytorch::cpuonly
  - black
  - pytest
  - pylint
  - pip