name: objaxdp
channels: 
  - conda-forge
  - pytorch
dependencies:
  - python==3.10
  - pytorch::pytorch==1.11
  - pytorch::torchvision
  - conda-forge::cudatoolkit
  - conda-forge::cudnn==8.2.1.32
  - conda-forge::wandb
  - conda-forge::scikit-learn
  - ipykernel
  - matplotlib
  - black
  - pytest
  - pylint
  - pip
  - pip: 
    - hydra-core==1.2.0
    - tqdm 
    - perflint
    - pytest-profiling
    - deepee