name: objaxdp
channels: 
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - pytorch::pytorch==2.0
  - pytorch-cuda=11.7
  - pytorch::torchvision
  - nvidia::cudatoolkit==11.4
  # - nvidia::cuda==11.4
  # - nvidia::cuda-nvcc==11.4.48
  # - nvidia/label/cuda-11.4.2::cuda-nvcc
  # - conda-forge::cudatoolkit-dev==11.4.0
  - conda-forge::cudnn==8.2.1.32
  - conda-forge::wandb
  - conda-forge::scikit-learn
  - conda-forge::scikit-image
  - conda-forge::nibabel
  - conda-forge::nilearn
  - nvidia::cuda-nvcc
  - ipykernel
  - matplotlib
  - conda-forge::h5py
  - conda-forge::pandas
  - conda-forge::opacus
  - conda-forge::seaborn
  - conda-forge::opencv
  - photosynthesis-team::piq
  - black
  - pytest
  - pylint
  - pip
  - pip: 
    - hydra-core==1.2.0
    - tqdm 
    - perflint
    - pytest-profiling
    - deepee
    - git+https://github.com/cs-mshah/split-folders
    - pyyaml