project: dptraining
dataset: CIFAR10
log_wandb: True
hyperparams:
  epochs: 90
  batch_size: 2000
  batch_size_test: 200
  lr: 0.1
  momentum: 0.9
scheduler:
  type: cosine
DP:
  disable_dp: False
  sigma: 1.5
  max_per_sample_grad_norm: 10.0
  delta: 1e-5
  norm_acc: False