defaults:
  - base_config
  - _self_
project: CelebA-DP
general:
  log_wandb: False
  parallel: False
  eval_train: False
  #use_pretrained_model: 
  #save_path: cifar10dp.npz
# checkpoint:
#   logdir: cifar10dpckpts
#   keep_ckpts: 2
#   makedir: True
dataset: 
  task: binary_classification
  name: CelebA
  root: ./data
  train_val_split: 0.9
  normalization: True
  fft: False
  has_group_attributes: True
metrics:
  main: 
    accuracy_score:
  logging:
    precision_score:
    classification_report:
      output_dict: True
      zero_division: 0
    class_accuracy_score:
loader: 
  num_workers: 16
  prefetch_factor: 12
  collate_fn: numpy
# augmentations:
#   consecutive_augmentations:
#     multiplicity: 2
#     consecutive_augmentations:
#       random_img_shift:
#         max_shift: 4
#       random_vertical_flips:
#         flip_prob: 0.5
model:
  name: resnet9
  in_channels: 3
  num_classes: 1
  conv: convws_nw
  activation: mish
  normalization: gn
  pooling: avgpool
  ensemble: 1
  extra_args:
    scale_norm: True
optim:
  name: nadam
loss: 
  type: bcse
  reduction: mean
ema:
  use_ema: False
  decay: 0.001
hyperparams:
  epochs: 50
  batch_size: 256
  batch_size_test: 512
  lr: 2e-3
  eval_every_n: 20
  # momentum: 0.9
scheduler:
  type: reduceonplateau
  normalize_lr: False
  patience: 5
  min_delta: 0.01
  factor: 0.5
DP:
  epsilon: 8
  max_per_sample_grad_norm: 1.0
  delta: 1e-5 
 
