project: cifar-DP
general:
  log_wandb: False
  parallel: False
  eval_train: True
dataset: 
  name: CIFAR10
  root: ./data
  train_val_split: 0.9
loader: 
  num_workers: 16
  prefetch_factor: 16
  collate_fn: numpy
augmentations:
  consecutive_augmentations: # combined
    - stack_augmentations
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
    - consecutive_augmentations: # combined
        random_img_shift:
          max_shift: 4
        random_vertical_flips:
          flip_prob: 0.5
model:
  name: resnet9
  in_channels: 3
  num_classes: 10
  activation: mish
  normalization: gn
  pooling: avgpool
  scale_norm: True
optim:
  name: nadam
ema:
  use_ema: False
  decay: 0.999
hyperparams:
  epochs: 200
  batch_size: 256
  batch_size_test: 512
  lr: 2e-3
  # momentum: 0.9
scheduler:
  type: reduceonplateau
  normalize_lr: False
  patience: 20
  min_delta: 0.01
  factor: 0.5
# earlystopping:
#   mode: maximize
#   patience: 100
#   min_delta: 0.01
DP:
  disable_dp: False
  epsilon: 7.5
  max_per_sample_grad_norm: 1.0
  delta: 1e-5
  norm_acc: False
  grad_acc_steps: 8