project: dptraining
dataset: 
  name: CIFAR10
  root: ./data
loader: 
  num_workers: 3
augmentations:
  random_vertical_flips:
      flip_prob: 0.5
  random_horizontal_flips:
      flip_prob: 0.5
  random_img_shift:
      img_shape: 
        - 3
        - 32
        - 32
model:
  name: cifar10model
  in_channels: 3
  num_classes: 10
log_wandb: False
hyperparams:
  epochs: 90
  batch_size: 2000
  batch_size_test: 200
  lr: 0.1
  momentum: 0.9
scheduler:
  type: cosine
  normalize_lr: True
DP:
  disable_dp: False
  epsilon: 7.5
  max_per_sample_grad_norm: 10.0
  delta: 1e-5
  norm_acc: False