defaults:
  - base_config
  - _self_
project: cifar
general:
  log_wandb: False
  parallel: False
  eval_train: True
dataset: 
  task: multi_class_classification
  name: CIFAR10
  root: ./data
  train_val_split: 0.9
  normalization: True
metrics:
  main: 
    accuracy_score: 
  logging:
    classification_report:
      output_dict: True
      zero_division: 0
loader: 
  num_workers: 16
  prefetch_factor: 16
  collate_fn: numpy
# augmentations:
# test_augmentations:
model:
  complex: False
  name: smoothnet
  in_channels: 3
  num_classes: 10
  conv: conv
  activation: mish
  normalization: gn
  pooling: avgpool
  extra_args:
    scale_norm: True
optim:
  name: nadam
loss: 
  type: cse
  reduction: sum
ema:
  use_ema: True
  decay: 0.995
hyperparams:
  epochs: 50
  batch_size: 512
  batch_size_test: 512
  lr: 2e-3
  # momentum: 0.9
scheduler:
  type: reduceonplateau
  normalize_lr: False
  patience: 5
  min_delta: 0.01
  factor: 0.9
earlystopping:
  mode: maximize
  patience: 100
  min_delta: 0.01
