program: dptraining/train.py
project: cifar10-DP
method: bayes
metric: 
  name: val.accuracy_score
  goal: maximize
parameters:
  augmentations.consecutive_augmentations.consecutive_augmentations.random_img_shift.max_shift:
    distribution: int_uniform
    min: 0
    max: 10
  augmentations.consecutive_augmentations.consecutive_augmentations.random_vertical_flips.flip_prob:
    distribution: uniform
    min: 0
    max: 1
  model.conv:
    values:
      - conv
      - convws
      - convws_nw
  scheduler.patience:
    distribution: int_uniform
    min: 5
    max: 50
  hyperparams.lr:
    distribution: uniform
    min: 4e-4
    max: 6e-3
name:
  "WRN16-4 sweep"

command:
  - ${env}
  - python
  - ${program}
  - -cn 
  - cifar10_dp_wrn.yaml
  - general.log_wandb=True
  - general.parallel=False
  - ${args_no_hyphens}
