defaults:
  - base_config
  - _self_
general:
  log_wandb: False
  parallel: False
  eval_train: True
  eval_init: False
  # save_path: cifar10_attack_data
wandb:
  project: cifar_mia
dataset: 
  task: classification
  name: attack
  attack:
    attack_data_path: cifar10_attack_data_2000_1000_samples.pt
    # pca_dim: 100
    # rescale_params: True
    # # pca_imgs: 100
    # rescale_images: True
    # include_eval_data_in_rescale_and_pca: False
    attack_input: outputs_and_grads
metrics:
  main: 
    roc_auc_score: 
  logging:
    roc_auc_score:
    accuracy_score:
    classification_report:
      output_dict: True
      zero_division: 0
    matthews_corrcoef:
loader: 
  num_workers: 0
  # prefetch_factor: 16
  # collate_fn: mia
  collate_fn: numpy
# augmentations:
# test_augmentations:
model:
  complex: False
  name: miacomparison
optim:
  name: nadam
loss: 
  type: cse
  reduction: sum
  binary_loss: True
# ema:
#   use_ema: True
#   decay: 0.995
hyperparams:
  epochs: 100
  batch_size: 20
  batch_size_test: 1024
  lr: 2e-3
  # momentum: 0.9
  grad_acc_steps: 1
attack:
  type: MIA_INFORMED
  # weight_model:
  #   complex: False
  #   name: mlp
  #   activation: elu
  #   extra_args:
  #     inp_size: 100
  #     outp_size: 50
  #     sizes:
  #       - 100
  # img_model:
  #   complex: False
  #   name: mlp
  #   activation: elu
  #   extra_args:
  #     inp_size: 3072
  #     outp_size: 50
  #     sizes:
  #       - 100
  compare_model:
    complex: False
    name: mlp
    activation: leakyrelu
    extra_args:
      inp_size: 14
      outp_size: 1
      sizes:
        - 100
        - 10
  orig_model:
    complex: False
    name: mlp
    activation: elu
    extra_args:
      sizes: 
        - 100
      inp_size: 3072
      outp_size: 10
  orig_loss_fn: 
    type: cse
    reduction: sum
    binary_loss: False
    
