program: dptraining/train.py
project: cifar-DP
method: grid
metric: 
  name: val.accuracy
  goal: maximize
parameters: 
  model.conv:
    values:
    - conv
    - convws
    - convws_nw
  model.name: 
    values:
    - resnet9
    - resnet18
    - wide_resnet
command:
  - ${env}
  - python
  - ${program}
  - -cn 
  - cifar10_dp.yaml
  - general.log_wandb=True
  - ${args_no_hyphens}