project: cifar-DP
general:
  log_wandb: False
  parallel: False
dataset: 
  name: CIFAR10
  root: ./data
  train_val_split: 0.9
loader: 
  num_workers: 2
  collate_fn: numpy
augmentations:
  # random_vertical_flips:
  #     flip_prob: 0.5
  # random_horizontal_flips:
  #     flip_prob: 0.5
  # random_img_shift:
  #     img_shape: 
  #       - 3
  #       - 32
  #       - 32
model:
  name: resnet9
  in_channels: 3
  num_classes: 10
  activation: mish
  normalization: gn
  pooling: avgpool
  scale_norm: True
optim:
  name: nadam
hyperparams:
  epochs: 50
  batch_size: 1024
  batch_size_test: 200
  lr: 2e-3
  momentum: 0.9
scheduler:
  type: const
  normalize_lr: False
DP:
  disable_dp: False
  epsilon: 7.5
  max_per_sample_grad_norm: 3.0
  delta: 1e-5
  norm_acc: False
  grad_acc_steps: 1