project: cifar-complex
general:
  log_wandb: False
  parallel: False
dataset: 
  name: CIFAR10
  root: ./data
  train_val_split: 0.9
loader: 
  num_workers: 16
  prefetch_factor: 16
  collate_fn: numpy
augmentations:
  make_complex_both:
test_augmentations:
  make_complex_both:
model:
  complex: True
  name: resnet9
  in_channels: 3
  num_classes: 10
  conv: convws
  activation: conjmish
  normalization: gnw
  pooling: avgpool
  scale_norm: True
optim:
  name: nadam
ema:
  use_ema: False
  decay: 0.999
hyperparams:
  epochs: 100
  batch_size: 1024
  batch_size_test: 512
  lr: 2e-3
  # momentum: 0.9
scheduler:
  type: reduceonplateau
  normalize_lr: False
  patience: 20
  min_delta: 0.01
  factor: 0.5
# earlystopping:
#   mode: maximize
#   patience: 100
#   min_delta: 0.01
DP:
  disable_dp: True