program: dptraining/train.py
method: bayes
metric: 
  name: val.accuracy
  goal: maximize
parameters: 
  DP.max_per_sample_grad_norm:
    min: 0.01
    max: 1.0
    distribution: log_uniform_values
command:
  - ${env}
  - python
  - ${program}
  - -cn 
  - cifar10_dp.yaml
  - general.log_wandb=True
  - ${args_no_hyphens}