program: dptraining/train.py
project: cifar10-DP
method: bayes
metric: 
  name: val.accuracy_score
  goal: maximize
parameters: 
  DP.alpha:
      min: 0.05
      max: 1.0
name:
  "BAM-sweep: alpha-value"
command:
  - ${env}
  - python
  - ${program}
  - -cn 
  - cifar10_dp.yaml
  - general.log_wandb=True
  - general.parallel=False
  - ${args_no_hyphens}
