defaults:
  - base_config
  - _self_
general:
  log_wandb: False
  parallel: False
  eval_train: False
  eval_init: False
  save_path: cifar10_attack_data
wandb:
  project: cifar_attack_generation
dataset: 
  task: classification
  name: CIFAR10
  root: ./data
  train_val_split: 0.9
  normalization: True
metrics:
  main: 
    accuracy_score: 
  logging:
    classification_report:
      output_dict: True
      zero_division: 0
loader: 
  num_workers: 16
  prefetch_factor: 16
  collate_fn: numpy
# augmentations:
# test_augmentations:
model:
  complex: False
  name: resnet9
  in_channels: 3
  num_classes: 10
  conv: convws_nw
  activation: mish
  normalization: gn
  pooling: avgpool
  extra_args:
    scale_norm: True
optim:
  name: nadam
loss: 
  type: cse
  reduction: sum
  binary_loss: False
ema:
  use_ema: True
  decay: 0.995
hyperparams:
  epochs: 2
  batch_size: 1024
  batch_size_test: 1024
  lr: 2e-3
  # momentum: 0.9
  grad_acc_steps: 2
attack:
  type: RECON_INFORMED
  N_fixed_dataset: 40000
  N_shadow_train: 10
  N_attack_eval: 10
  
