defaults:
  - base_config
  - _self_
project: cifar10-DP
general:
  log_wandb: True
  parallel: False
  eval_train: False
  #use_pretrained_model: 
  #save_path: cifar10dp.npz
# checkpoint:
#   logdir: cifar10dpckpts
#   keep_ckpts: 2
#   makedir: True
dataset: 
  task: classification
  name: CIFAR10
  root: ./data
  train_val_split: 0.9
  normalization: True
  fft: False
  undersample_class: False
  undersample_factor: 0.0
metrics:
  main: 
    accuracy_score: 
  logging:
    classification_report:
      output_dict: True
      zero_division: 0
loader: 
  num_workers: 16
  prefetch_factor: 32
  collate_fn: numpy
augmentations:
  consecutive_augmentations:
    multiplicity: 2
    consecutive_augmentations:
      random_img_shift:
        max_shift: 4
      random_vertical_flips:
        flip_prob: 0.5
model:
  name: resnet9
  in_channels: 3
  num_classes: 10
  conv: convws_nw
  activation: mish
  normalization: gn
  pooling: avgpool
  # extra_args:
  #   scale_norm: True
  #   width: 4
  #   depth: 40
optim:
  name: nadam
loss: 
  type: cse
  reduction: mean
ema:
  use_ema: True
  decay: 0.0001
hyperparams:
  epochs: 30
  batch_size: 256
  batch_size_test: 512
  lr: 2e-3
  eval_every_n: 50
  # momentum: 0.9
scheduler:
  type: reduceonplateau
  normalize_lr: False
  patience: 15
  min_delta: 0.01
  factor: 0.5
DP:
  epsilon: 8
  max_per_sample_grad_norm: 1.0
  delta: 1e-5
  norm_acc: False
  grad_acc_steps: 8
  rsqrt_noise_adapt: False
  glrt_assumption: False
  bam: False
  SAT: True
  r: 0.025
 
