program: dptraining/train.py
project: cifar-DP-complex
method: bayes
metric: 
  name: val.accuracy
  goal: maximize
parameters: 
  augmentations.consecutive_augmentations.multiplicity:
    distribution: int_uniform
    min: 1
    max: 32
  augmentations.consecutive_augmentations.consecutive_augmentations.random_img_shift.max_shift:
    distribution: int_uniform
    min: 0
    max: 10
  augmentations.consecutive_augmentations.consecutive_augmentations.random_vertical_flips.flip_prob:
    distribution: uniform
    min: 0
    max: 1
  model.name:
    values: 
      - resnet9
      - resnet18
      - wide_resnet
  loss.reduction:
    values:
      - sum
      - mean
  DP.grad_acc_steps:
    distribution: int_uniform
    min: 1
    max: 1000
  model.conv:
    values:
      - conv
      - convws
      - convws_nw
command:
  - ${env}
  - python
  - ${program}
  - -cn 
  - cifar10_complex_dp.yaml
  - general.log_wandb=True
  - general.parallel=False
  - ${args_no_hyphens}
