defaults:
  - base_config
  - _self_
general:
  log_wandb: False
  parallel: False
  eval_train: True
wandb:
  project: imagefolder
dataset: 
  task: classification
  name: imagefolder
  root: ./data/group
  train_val_split: 1
  test_split: 0
metrics:
  main: 
    accuracy_score: 
  logging:
    classification_report:
      output_dict: True
      zero_division: 0
loader: 
  num_workers: 0
  collate_fn: numpy
train_transforms:
  Resize: 
      size: 224
  CenterCrop:
      size: 224
  pil_to_jax:
  numpy_img_to_chw:
model:
  name: resnet9
  in_channels: 3
  num_classes: 1
  conv: convws_nw
  activation: mish
  normalization: gn
  pooling: maxpool
  extra_args:
    scale_norm: True
optim:
  name: nadam
loss: 
  type: cse
  reduction: sum
  binary_loss: True
hyperparams:
  epochs: 1
  batch_size: 1
  batch_size_test: 512
  lr: 2e-3
  # momentum: 0.9
  grad_acc_steps: 29
DP:
  epsilon: 8
  max_per_sample_grad_norm: 1
  delta: 0.01
  norm_acc: False
  mechanism: rdp
  use_batch_sampling: False
