defaults:
  - base_config
  - _self_
project: imagenet-dp
general:
  log_wandb: False
  parallel: False
  eval_train: False
dataset: 
  task: multi_class_classification
  name: imagenet
  root: ./data/ILSVRC2012
  train_val_split: 0.9
metrics:
  main: 
    accuracy_score: 
  logging:
    classification_report:
      output_dict: True
      zero_division: 0
train_transforms:
  Resize: 
      size: 224
  RandomCrop:
      size: 224
  pil_to_numpy:
  numpy_img_to_chw:
test_transforms:
  Resize: 
      size: 224
  CenterCrop:
      size: 224
  pil_to_numpy:
  numpy_img_to_chw:
loader:
  collate_fn: numpy
  num_workers: 32
  prefetch_factor: 2
  pin_memory: True
augmentations:
  pil_to_jax:
  normalize_jax:
      mean:
        - 0.485
        - 0.456
        - 0.406
      std:
        - 0.229
        - 0.224
        - 0.225 
  make_complex_both:
  # random_vertical_flips:
  #     flip_prob: 0.5
  # random_horizontal_flips:
  #     flip_prob: 0.5
test_augmentations:
  pil_to_jax:
  normalize_jax:
      mean:
        - 0.485
        - 0.456
        - 0.406
      std:
        - 0.229
        - 0.224
        - 0.225 
  make_complex_both:
optim:
  name: nadam
loss: 
  type: cse
  reduction: sum
model:
  complex: True
  name: resnet9
  in_channels: 3
  num_classes: 1000
  conv: convws_nw
  activation: conjmish
  normalization: gnw
  pooling: avgpool
  scale_norm: True
ema:
  use_ema: False
  decay: 0.04
hyperparams:
  epochs: 200
  batch_size: 64
  batch_size_test: 256
  lr: 1e-3
scheduler:
  type: reduceonplateau
  normalize_lr: False
  patience: 20
  min_delta: 0.01
  factor: 0.5
DP:
  epsilon: 8.0
  max_per_sample_grad_norm: 1.0
  delta: 8e-7
  norm_acc: False
  grad_acc_steps: 64
  adapt_noise: True
