project: imagenet_dpsgd
log_wandb: True
dataset: 
  name: imagenet
  root: ./data/ILSVRC2012
train_transforms:
  Resize: 
      size: 224
  RandomCrop:
      size: 224
  ToTensor:
test_transforms:
  Resize: 
      size: 224
  CenterCrop:
      size: 224
  ToTensor:
loader:
  num_workers: 32
  prefetch_factor: 8
  pin_memory: True
augmentations:
  random_vertical_flips:
      flip_prob: 0.5
  random_horizontal_flips:
      flip_prob: 0.5
model:
  name: resnet18
  in_channels: 3
  num_classes: 1000
  normalization: gn
  activation: selu
hyperparams:
  epochs: 10
  batch_size: 200
  batch_size_test: 200
  lr: 0.1
  momentum: 0.9
scheduler:
  type: cosine
  normalize_lr: True
DP:
  disable_dp: False
  sigma: 1.5
  max_per_sample_grad_norm: 10.0
  delta: 1e-5
  norm_acc: False