project: imagenet_dpsgd
log_wandb: False
dataset: 
  name: imagenet
  root: ./data/ILSVRC2012
train_transforms:
  Resize: 
      size: 224
  RandomCrop:
      size: 224
  pil_to_numpy:
  numpy_img_to_chw:
test_transforms:
  Resize: 
      size: 224
  CenterCrop:
      size: 224
  pil_to_numpy:
  numpy_img_to_chw:
loader:
  num_workers: 16
  prefetch_factor: 8
  pin_memory: True
augmentations:
  normalize_np_img:
      mean:
        - 0.485
        - 0.456
        - 0.406
      std:
        - 0.229
        - 0.224
        - 0.225 
  random_vertical_flips:
      flip_prob: 0.5
  random_horizontal_flips:
      flip_prob: 0.5
test_augmentations:
  normalize_np_img:
      mean:
        - 0.485
        - 0.456
        - 0.406
      std:
        - 0.229
        - 0.224
        - 0.225 
optim:
  name: nadam
model:
  name: resnet18
  in_channels: 3
  num_classes: 1000
  normalization: gn
  activation: selu
hyperparams:
  epochs: 3
  batch_size: 512
  batch_size_test: 256
  optim: Adam
  lr: 1e-3
  momentum: 0.9
scheduler:
  type: cosine
  normalize_lr: True
DP:
  disable_dp: False
  epsilon: 10
  max_per_sample_grad_norm: 1.0
  delta: 1e-5
  norm_acc: False