project: imagenet_dpsgd
log_wandb: False
dataset: 
  name: imagenet
  root: ./data/ILSVRC2012
train_transforms:
  Resize: 
      size: 224
  RandomCrop:
      size: 224
  ToTensor:
test_transforms:
  Resize: 
      size: 224
  CenterCrop:
      size: 224
  ToTensor:
loader:
  num_workers: 16
  prefetch_factor: 8
  pin_memory: True
augmentations:
  random_vertical_flips:
      flip_prob: 0.5
  random_horizontal_flips:
      flip_prob: 0.5
model:
  name: resnet18
  in_channels: 3
  num_classes: 1000
  normalization: gn
  activation: selu
hyperparams:
  epochs: 3
  batch_size: 512
  batch_size_test: 256
  lr: 1e-3
  momentum: 0.9
scheduler:
  type: cosine
  normalize_lr: True
DP:
  disable_dp: False
  epsilon: 10
  max_per_sample_grad_norm: 1.0
  delta: 1e-5
  norm_acc: False