defaults:
  - base_config
  - _self_
project: imagenet-complex
general:
  log_wandb: False
  parallel: False
  eval_train: False
dataset: 
  task: multi_class_classification
  name: imagenet
  root: ./data/ILSVRC2012
  train_val_split: 0.9
metrics:
  main: 
    accuracy_score: 
  logging:
    classification_report:
      output_dict: True
      zero_division: 0
train_transforms:
  Resize: 
      size: 224
  RandomCrop:
      size: 224
  pil_to_numpy:
  numpy_img_to_chw:
test_transforms:
  Resize: 
      size: 224
  CenterCrop:
      size: 224
  pil_to_numpy:
  numpy_img_to_chw:
loader:
  collate_fn: numpy
  num_workers: 16
  prefetch_factor: 32
  pin_memory: True
augmentations:
  normalize_np_img:
      mean:
        - 0.485
        - 0.456
        - 0.406
      std:
        - 0.229
        - 0.224
        - 0.225 
  make_complex_both:
test_augmentations:
  normalize_np_img:
      mean:
        - 0.485
        - 0.456
        - 0.406
      std:
        - 0.229
        - 0.224
        - 0.225 
  make_complex_both:
model:
  complex: True
  name: resnet18
  in_channels: 3
  num_classes: 1000
  conv: convws
  activation: conjmish
  normalization: gnw
  pooling: avgpool
  scale_norm: True
optim:
  name: nadam
ema:
  use_ema: False
  decay: 0.999
hyperparams:
  epochs: 10
  batch_size: 512
  batch_size_test: 128
  lr: 2e-3
  # momentum: 0.9
scheduler:
  type: reduceonplateau
  normalize_lr: False
  patience: 20
  min_delta: 0.01
  factor: 0.5
# earlystopping:
#   mode: maximize
#   patience: 100
#   min_delta: 0.01
