project: MedMNIST
general:
  log_wandb: True
  parallel: False
dataset: 
  name: pneumoniamnist
  root: ./data/
  normalization: True
loader: 
  num_workers: 16
  prefetch_factor: 16
  collate_fn: numpy
augmentations:
  # make_complex_both:
test_augmentations:
  # make_complex_both:
model:
  complex: False
  name: resnet18
  in_channels: 1
  num_classes: 2
  conv: conv
  activation: mish
  normalization: gn
  pooling: maxpool
  # scale_norm: True
optim:
  name: nadam
loss: 
  type: cse
  reduction: sum
ema:
  use_ema: True
  decay: 0.995
hyperparams:
  epochs: 100
  batch_size: 128
  loss: 
  type: cse
  reduction: sum
  batch_size_test: 128
  lr: 1e-3
  # momentum: 0.9
scheduler:
  type: reduceonplateau
  normalize_lr: False
  patience: 5
  min_delta: 0.01
  factor: 0.9
earlystopping:
  mode: maximize
  patience: 100
  min_delta: 0.01
DP:
  disable_dp: True
