defaults:
  - base_config
  - _self_
project: mimic-DP
general:
  log_wandb: False
  parallel: False
  eval_train: False
dataset: 
  task: binary_classification
  name: mimic
  root: /home/moritz/data/mimic-cxr-jpg-224/
  has_group_attributes: True
metrics:
  main: 
    accuracy_score: 
  logging:
    classification_report:
      output_dict: False
      zero_division: 0
loader: 
  num_workers: 16
  prefetch_factor: 12
  collate_fn: numpy
# augmentations:
#   consecutive_augmentations:
#     multiplicity: 1
#     consecutive_augmentations:
#       random_img_shift:
#         max_shift: 4
#       random_vertical_flips:
#         flip_prob: 0.5
model:
  name: resnet9
  in_channels: 1
  num_classes: 1
  conv: convws_nw
  activation: mish
  normalization: gn
  pooling: avgpool
  ensemble: 1
  extra_args:
    scale_norm: True
optim:
  name: nadam
loss: 
  type: bcse
  reduction: mean
ema:
  use_ema: False
  decay: 0.001
hyperparams:
  epochs: 50
  batch_size: 2
  batch_size_test: 512
  lr: 1e-3
  eval_every_n: 1_000
  # momentum: 0.9
scheduler:
  type: reduceonplateau
  normalize_lr: False
  patience: 5
  min_delta: 0.01
  factor: 0.5
DP:
  epsilon: 8
  max_per_sample_grad_norm: 10.0
  delta: 1e-5
  clip_only: True
  grad_acc_steps: 10
 
