defaults:
  - base_config
  - _self_
general:
  log_wandb: False
  parallel: False
  eval_train: True
  make_save_str_unique: True
  eval_init: False
  # use_pretrained_model: msd_pancreas_unet_4-3-convwsnw_mp_gn_mish_resilient-flower-4_2023-01-04_11-51-58.npz
wandb:
  project: msd_dp
# ckpt:
#   logdir: msd_ckpts
#   keep_ckpts: 2
#   makedir: True
dataset: 
  task: segmentation
  name: msd
  root: ./data/MSD/
  train_val_split: 0.9
  nifti_seg_options:
    database: ./data/MSD/Task03_Liver/db.hdf5
    test_split: 0.1
    msd_subtask: liver
    normalization_type: gaussian
    data_stats:
      mean: -81.91
      std: 8.736
    ct_window: 
      low: -150
      high: 200
    assume_same_settings: False
loader: 
  num_workers: 4
  prefetch_factor: 2
  collate_fn: numpy
train_transforms:
  random_crop:
    apply_to: 'images_and_labels'
    size:
      - 128
      - 128
      - 50
# augmentations:
#   consecutive_augmentations:
#     multiplicity: 2
#     apply_to: 'images_and_labels'
#     augmentations:
#       random_crop:
#         size:
#           - 128
#           - 128
#           - 50
model:
  dim3: True
  name: unet
  in_channels: 1
  activation: mish
  conv: convws_nw
  upconv: convws_nw
  pooling: maxpool
  normalization: gn
  extra_args:
    out_channels: 3
    channels: 4
optim:
  name: nadam
loss: 
  type: dice
  reduction: mean
  binary_loss: False
  class_weights: 
    - 0.5
    - 0.5
    - 15
# ema:
#   use_ema: False
#   decay: 0.999
hyperparams:
  epochs: 50
  batch_size: 1
  batch_size_test: 1
  lr: 2e-3
  # momentum: 0.9
  # l2regularization: 1e-5
  # overfit: 2
  grad_acc_steps: 1
metrics:
  main:     
    fscore_avg:
  logging:
    fscore_avg:
    weighted_fscore_avg:
    fscore:
    mean_squared_error:
    # mean_absolute_error:
  per_batch_metrics: True
# scheduler:
#   type: reduceonplateau
#   normalize_lr: False
#   patience: 20
#   min_delta: 0.01
#   factor: 0.5
DP:
  epsilon: 8.0
  max_per_sample_grad_norm: 1.0
  delta: 8e-7
  norm_acc: False