defaults:
  - base_config
  - _self_
project: msd_dp
general:
  log_wandb: False
  parallel: False
  eval_train: True
  make_save_str_unique: True
  eval_init: True
  # use_pretrained_model: msd_pancreas_unet_4-1-convwsnw_mp_gn_mish_dainty-jazz-3_2023-01-03_15-13-57.npz
# ckpt:
#   logdir: msd_ckpts
#   keep_ckpts: 2
#   makedir: True
dataset: 
  task: segmentation
  name: msd
  root: ./data/MSD/
  train_val_split: 0.9
  msd:
    test_split: 0.1
    resolution: 128
    subtask: liver
    cache: True
    # slice_thickness: 1.0
    normalization_type: gaussian
    n_slices: 50
    data_stats:
      mean: -81.91
      std: 8.736
    ct_window: 
      low: -150
      high: 200
loader: 
  num_workers: 16
  prefetch_factor: 2
  collate_fn: numpy
model:
  dim3: True
  name: unet
  in_channels: 1
  activation: mish
  conv: convws_nw
  upconv: convws_nw
  pooling: maxpool
  normalization: gn
  extra_args:
    out_channels: 3
    channels: 4
optim:
  name: nadam
loss: 
  type: dice
  reduction: mean
  binary_loss: False
ema:
  use_ema: False
  decay: 0.999
hyperparams:
  epochs: 10
  batch_size: 1
  batch_size_test: 1
  lr: 2e-3
  # momentum: 0.9
  # l2regularization: 1e-5
  # overfit: 2
metrics:
  main:     
    fscore_avg:
  logging:
    fscore_avg:
    weighted_fscore_avg:
    fscore:
    mean_squared_error:
    # mean_absolute_error:
  per_batch_metrics: True
scheduler:
  type: reduceonplateau
  normalize_lr: False
  patience: 20
  min_delta: 0.01
  factor: 0.5
DP:
  epsilon: 8.0
  max_per_sample_grad_norm: 1.0
  delta: 8e-7
  norm_acc: False
  grad_acc_steps: 8