project: cifar
general:
  log_wandb: False
  parallel: False
dataset: 
  name: radimagenet
  task: classification
  root: ./data/radiology_ai
  train_val_split: 0.8
  test_split: 0.1
  split: stratified
  datasplit_seed: 0
  modality: all
  allowed_body_regions: all
  allowed_labels: all
loader: 
  num_workers: 16
  prefetch_factor: 16
  collate_fn: numpy
augmentations:
  normalize_jax:
      mean:
        - 0.22039941
      std:
        - 0.24865805
test_augmentations:
  normalize_jax:
      mean:
        - 0.22039941
      std:
        - 0.24865805
model:
  name: resnet9
  in_channels: 1
  num_classes: 165
  conv: conv
  activation: mish
  normalization: bn
  pooling: maxpool
  # scale_norm: True
optim:
  name: nadam
ema:
  use_ema: True
  decay: 0.995
hyperparams:
  epochs: 50
  batch_size: 32
  batch_size_test: 512
  lr: 2e-3
  # momentum: 0.9
loss: 
  type: cse
  reduction: sum
scheduler:
  type: reduceonplateau
  normalize_lr: False
  patience: 5
  min_delta: 0.01
  factor: 0.9
earlystopping:
  mode: maximize
  patience: 100
  min_delta: 0.01
DP:
  disable_dp: True