defaults:
  - base_config
  - _self_
general:
  log_wandb: False
  parallel: False
  eval_train: True
  # save_path: radimagenet_resnet9.npz
#  make_save_str_unique: True
#  use_pretrained_model: imagenet_resnet9_convws_nw_gn_mp_sn.npz
# checkpoint:
#   logdir: radimagenet_resnet9_ckpt
#   keep_ckpts: 10
#   makedir: True
wandb:
  project: radimagenet
dataset: 
  name: radimagenet
  task: classification
  root: ./data/radiology_ai
  radimagenet:
    normalize_by_modality: True
    modality: all
    allowed_body_regions: all
    allowed_labels: all
loader: 
  num_workers: 32
  prefetch_factor: 16
  collate_fn: numpy
  pin_memory: True
augmentations:
  normalize_jax:
      mean:
        - 0.22039941
      std:
        - 0.24865805
  random_vertical_flips:
    flip_prob: 0.5
  random_horizontal_flips:
    flip_prob: 0.5
  # gaussiannoise:
  #   std: 0.01
test_augmentations:
  normalize_jax:
      mean:
        - 0.22039941
      std:
        - 0.24865805
model:
  name: wide_resnet
  in_channels: 1
  num_classes: 165
  conv: convws_nw
  activation: mish
  normalization: bn
  pooling: maxpool
  extra_args:
    # scale_norm: True
    depth: 40
    width: 4
  #pretrained_model_changes:
  #  in_channels: 1
  #  num_classes: 165
  #  only_finetune: False
#unfreeze_schedule:
#  trigger_points: 
#    - 2
#    - 4
#    - 6
#scheduler:
#  type: manual
#  epoch_triggers:
#    - 2
#    - 4
#    - 6
#  lr_list:
#    - 1e-3
#    - 1e-4
#    - 1e-5
optim:
  name: nadam
#ema:
#  use_ema: True
#  decay: 0.995
hyperparams:
  epochs: 200
  batch_size: 16
  batch_size_test: 64
  lr: 2e-3
  # overfit: 10
  # momentum: 0.9
  grad_acc_steps: 32
metrics:
  main: 
    matthews_corrcoef:
  logging:
    classification_report:
      output_dict: True
      zero_division: 0
    accuracy_score: 
loss: 
  type: cse
  reduction: sum
  binary_loss: False
  # calculate_class_weights: True
# scheduler:
#   type: reduceonplateau
#   normalize_lr: False
#   patience: 5
#   min_delta: 0.01
#   factor: 0.9
earlystopping:
  mode: maximize
  patience: 10
  min_delta: 0.001