defaults:
  - base_config
  - _self_
general:
  log_wandb: False
  parallel: False
  eval_train: True
  # save_path: radimagenet_resnet9.npz
  make_save_str_unique: True
  use_pretrained_model: imagenet_resnet9_convws_nw_gn_mp_sn.npz
# checkpoint:
#   logdir: radimagenet_resnet9_ckpt
#   keep_ckpts: 10
#   makedir: True
wandb:
  project: radimagenet
dataset: 
  name: radimagenet
  task: classification
  root: ./data/radiology_ai
  train_val_split: 0.8
  test_split: 0.1
  datasplit_seed: 0
  radimagenet:
    normalize_by_modality: True
    modality: all
    allowed_body_regions: all
    allowed_labels: all
loader: 
  num_workers: 16
  prefetch_factor: 16
  collate_fn: numpy
  pin_memory: True
augmentations:
  normalize_jax:
      mean:
        - 0.22039941
      std:
        - 0.24865805
test_augmentations:
  normalize_jax:
      mean:
        - 0.22039941
      std:
        - 0.24865805
model:
  name: resnet9
  in_channels: 3
  num_classes: 1000
  conv: convws_nw
  activation: mish
  normalization: gn
  pooling: maxpool
  extra_args:
    scale_norm: True
  #   depth: 40
  #   width: 4
  pretrained_model_changes:
    in_channels: 1
    num_classes: 165
    only_finetune: False
unfreeze_schedule:
  trigger_points: 
    - 2
    - 4
    - 6
scheduler:
  type: manual
  epoch_triggers:
    - 2
    - 4
    - 6
  lr_list:
    - 1e-3
    - 1e-4
    - 1e-5
optim:
  name: nadam
ema:
  use_ema: True
  decay: 0.995
hyperparams:
  epochs: 10
  batch_size: 64
  batch_size_test: 128
  lr: 2e-3
  # overfit: 10
  # momentum: 0.9
metrics:
  main: 
    accuracy_score: 
  logging:
    classification_report:
      output_dict: True
      zero_division: 0
    matthews_corrcoef:
loss: 
  type: cse
  reduction: sum
  binary_loss: False
# scheduler:
#   type: reduceonplateau
#   normalize_lr: False
#   patience: 5
#   min_delta: 0.01
#   factor: 0.9
# earlystopping:
#   mode: maximize
#   patience: 100
#   min_delta: 0.01