defaults:
  - base_config
  - _self_
general:
  log_wandb: False
  parallel: False
  eval_train: True
  make_save_str_unique: True
  # use_pretrained_model: imagenet_resnet9_convws_nw_gn_mp_sn.npz
# checkpoint:
#   logdir: radimagenet_resnet9_ckpt
#   keep_ckpts: 10
#   makedir: True
wandb:
  project: radimagenet-DP
dataset: 
  name: radimagenet
  task: classification
  root: ./data/radiology_ai
  train_val_split: 0.8
  test_split: 0.1
  datasplit_seed: 0
  radimagenet:
    normalize_by_modality: True
    modality: all
    allowed_body_regions: all
    allowed_labels: all
loader: 
  num_workers: 32
  prefetch_factor: 16
  collate_fn: numpy
  pin_memory: True
augmentations:
  consecutive_augmentations:
    normalize_jax:
        mean:
          - 0.22039941
        std:
          - 0.24865805
    # consecutive_augmentations:
    #   multiplicity: 16
    #   consecutive_augmentations:
    #     random_horizontal_flips:
    #       flip_prob: 0.2
    #     random_vertical_flips:
    #       flip_prob: 0.2
test_augmentations:
  normalize_jax:
      mean:
        - 0.22039941
      std:
        - 0.24865805
model:
  name: resnet9
  in_channels: 1
  num_classes: 165
  conv: convws_nw
  activation: mish
  normalization: gn
  pooling: maxpool
  extra_args:
    # depth: 40
    # width: 4
    scale_norm: True
#   pretrained_model_changes:
#     in_channels: 1
#     num_classes: 165
#     # only_finetune: True
# unfreeze_schedule:
#   trigger_points: 
#     - 2
#     - 4
#     - 6
optim:
  name: nadam
ema:
  use_ema: True
  decay: 0.995
hyperparams:
  epochs: 10
  batch_size: 64
  batch_size_test: 128
  lr: 2e-3
  # overfit: 256
  # momentum: 0.9
  grad_acc_steps: 120
metrics:
  main: 
    accuracy_score: 
  logging:
    classification_report:
      output_dict: True
      zero_division: 0
    matthews_corrcoef:
loss: 
  type: cse
  reduction: sum
  binary_loss: False
DP:
  epsilon: 8.0
  max_per_sample_grad_norm: 1.0
  delta: 8e-7
  norm_acc: False
  # mechanism: rdp