defaults:
  - base_config
  - _self_
project: radimagenet_recon
general:
  log_wandb: False
  parallel: False
  eval_train: True
  save_path: radimagenet_unet.npz
  make_save_str_unique: True
checkpoint:
  logdir: radimagenet_unet_ckpt
  keep_ckpts: 10
  makedir: True
dataset: 
  name: radimagenet
  task: reconstruction
  root: ./data/radiology_ai
  train_val_split: 0.8
  test_split: 0.1
  radimagenet:
    normalize_by_modality: False
    datasplit_seed: 0
    modality: all
    allowed_body_regions: all
    allowed_labels: all
loader: 
  num_workers: 16
  prefetch_factor: 16
  collate_fn: numpy
  pin_memory: True
augmentations:
  normalize_jax:
      mean:
        - 0.22039941
      std:
        - 0.24865805
  gaussiannoise:
    std: 0.1
  randomphasejax:
    control_points: 4
test_augmentations:
  normalize_jax:
      mean:
        - 0.22039941
      std:
        - 0.24865805
  gaussiannoise:
    std: 0.1
  randomphasejax:
    control_points: 4
label_augmentations:
  normalize_jax:
      mean:
        - 0.22039941
      std:
        - 0.24865805
  randomphasejax:
    control_points: 4
model:
  complex: True
  name: unet
  in_channels: 1
  activation: cardioid
  extra_args:
    out_channels: 1
    channels: 16
optim:
  name: nadam
ema:
  use_ema: True
  decay: 0.995
hyperparams:
  epochs: 10
  batch_size: 60
  batch_size_test: 128
  lr: 2e-3
  # overfit: 10
  # momentum: 0.9
loss: 
  type: l1
  reduction: sum
metrics:
  main: 
    structural_similarity:
      win_size: 7
      channel_axis: 0
      data_range: 8.48
  logging:
    mean_squared_error:
    structural_similarity:
      win_size: 7
      channel_axis: 0
      data_range: 8.48
    peak_signal_noise_ratio: 
      data_range: 8.48
  per_batch_metrics: True
scheduler:
  type: reduceonplateau
  normalize_lr: False
  patience: 5
  min_delta: 0.01
  factor: 0.9
earlystopping:
  mode: maximize
  patience: 100
  min_delta: 0.01