defaults:
  - base_config
  - _self_
general:
  log_wandb: False
  parallel: False
  eval_train: False
wandb:
  project: tinyimagenet-dp
dataset: 
  task: classification
  name: tinyimagenet
  root: ./data/ImageNet32
  version: 32
  train_val_split: 0.95
  normalization: True
metrics:
  main: 
    accuracy_score: 
  logging:
    classification_report:
      output_dict: True
      zero_division: 0
train_transforms:
  numpy_img_to_chw:
test_transforms:
  numpy_img_to_chw:
loader:
  collate_fn: numpy
  num_workers: 64
  prefetch_factor: 6
  pin_memory: True
augmentations:
  consecutive_augmentations:
    multiplicity: 16
    consecutive_augmentations:
      random_img_shift:
        max_shift: 4
      random_vertical_flips:
        flip_prob: 0.5
optim:
  name: nadam
loss: 
  type: cse
  reduction: sum
  binary_loss: False
model:
  name: wide_resnet
  in_channels: 3
  num_classes: 1000
  conv: conv
  activation: mish
  normalization: gn
  pooling: avgpool
  extra_args:
    scale_norm: True
    depth: 40
    width: 4
ema:
  use_ema: False
  decay: 0.04
hyperparams:
  epochs: 200
  batch_size: 32
  batch_size_test: 256
  lr: 1e-3
scheduler:
  type: reduceonplateau
  normalize_lr: False
  patience: 20
  min_delta: 0.01
  factor: 0.5
DP:
  epsilon: 8.0
  max_per_sample_grad_norm: 1.0
  delta: 8e-7
  norm_acc: False
  grad_acc_steps: 64
