defaults:
  - base_config
  - _self_
project: tinyimagenet-complex-dp
general:
  log_wandb: False
  parallel: False
  eval_train: False
dataset: 
  task: multi_class_classification
  name: tinyimagenet
  root: ./data/ImageNet32
  version: 32
  train_val_split: 0.95
  normalization: True
metrics:
  main: 
    accuracy_score: 
  logging:
    classification_report:
      output_dict: True
      zero_division: 0
train_transforms:
  numpy_img_to_chw:
test_transforms:
  numpy_img_to_chw:
loader:
  collate_fn: numpy
  num_workers: 64
  prefetch_factor: 6
  pin_memory: True
augmentations:
  make_complex_both:
  consecutive_augmentations:
    multiplicity: 16
    complex: True
    consecutive_augmentations:
      complex: True
      random_img_shift:
        max_shift: 4
      random_vertical_flips:
        flip_prob: 0.5
test_augmentations:
  make_complex_both: 
optim:
  name: nadam
loss: 
  type: cse
  reduction: sum
model:
  name: wide_resnet
  depth: 40
  width: 4
  complex: True
  in_channels: 3
  num_classes: 1000
  conv: convws_nw
  activation: conjmish
  normalization: gnw
  pooling: avgpool
  scale_norm: True
ema:
  use_ema: False
  decay: 0.04
hyperparams:
  epochs: 200
  batch_size: 16
  batch_size_test: 256
  lr: 1e-3
scheduler:
  type: reduceonplateau
  normalize_lr: False
  patience: 20
  min_delta: 0.01
  factor: 0.5
DP:
  epsilon: 8.0
  max_per_sample_grad_norm: 1.0
  delta: 8e-7
  norm_acc: False
  grad_acc_steps: 256
  rsqrt_noise_adapt: True
